### PR TITLE
MYNEWT-4: Need the concept of wallclock time

### PR DESCRIPTION
**Pull request by neelnatu**
Add shell command "date" to set and get wallclock time.

The wallclock time is specified as per RFC 3339. For example:

date 2016-03-02T22:44:00        # set time to Mar 2 2016 10:44 PM UTC
date 2016-03-02T22:44:00Z       # with explicit Zulu time zone (UTC + 0)
date 2016-03-02T22:44:00z       # with explicit Zulu time zone (UTC + 0)
date 2016-03-02T22:44:00-08:00  # pacific standard time (UTC - 0800)
date 2016-03-02T22:44:00+05:30  # indian standard time (UTC + 0530)
date 2016-03-02T22:44:00.000031 # time is 22:44:00 + 31 usec
date 2016-03-02T22:44:00.1      # time is 22:44:00 + 100 msec
date 2016-03-02T22:44:00.013    # time is 22:44:00 + 13 msec

'os_settimeofday()' and 'os_gettimeofday()' can be used to set and get
the time of day.

'parse_datetime()' and 'format_datetime()' are available to parse and
format the RFC 3339 compliant datetime strings.

### CODE REVIEW

**Comment by wes3** [comment]
Reviewed the code and it looks good. Very readable. I do have one question and a very nit-picky comment. The nit-picky comment: since I am very lazy it would have been nice to include an example of the date-time format, or maybe even just copy out section 5.6 of the RFC so someone would not have to go to a different place to look at the format. Yes, I am that lazy! :-)

My question is this: is struct clocktime something we made up? Just curious, as I wonder why some of the fields are ints instead of 8-bits? Probably not a big deal to save the memory...

**Comment by neelnatu** [comment]
I'll add the datetime format as a comment right above parse_datetime() so its easy to reference.

'struct clocktime' comes from FreeBSD (sys/kern/subr_clock.c). It is used by the functions 'clocktime_to_timeval()' and 'timeval_to_clocktime()' that I directly copied from FreeBSD so didn't want to make gratuitous changes to the size of the fields.

**Comment by wes3** [comment]
+1

Will

**Comment by justinmclean** [comment]
If some of the code come from FreeBSD be sure to abide by their license terms (which is fairly easy and Apache compatible).

**Comment by neelnatu** [comment]
Hi Justin,

On Thu, Mar 3, 2016 at 2:38 PM, Justin Mclean <notifications@github.com>
wrote:

> If some of the code come from FreeBSD be sure to abide by their license
> terms (which is fairly easy and Apache compatible).
>
The FreeBSD license is included in libs/os/include/os/os_time.h and
libs/util/src/datetime.c as required by that license. I also updated
LICENSES in the top level directory.

Let me know if I missed anything and I'll fix it.

best
Neel

**Comment by aditihilbert** [comment]
Neel, 

This pull request never registered with the asfgit, possibly because of the merge conflicts that you see right above this. So you will have to pull the most current repo content and push your changes to your fork so that the pull request can be generated correctly by github.

git pull --rebase upstream develop

In the future, it's best to create and push work to a feature-specific branch on your fork on github. That way you could delete this branch of your fork (on github) if something like this happens. It automatically deletes the pull request. Otherwise it is not possible to delete a pull request.

**Comment by justinmclean** [comment]
Hi,

> The FreeBSD license is included in libs/os/include/os/os_time.h and
> libs/util/src/datetime.c as required by that license. I also updated
> LICENSES in the top level directory.

Probably not quite correct as you have double headers on the files. While the software as a whole can be Apache licensed individual 3rd party files can be under other comparable licenses. But it can get a little tricky when your’ve taken a file and modified it - for Apache policy see [1]. 

From [1] 1) do not remove license or copyright notices. 2) make sure the full text of the license in included somewhere 3) don’t add an Apache header unless major modifications have been made. We’re good with the first two points but the 3rd may need fixing.

How much of those files are original?

Thanks,
Justin

1. http://www.apache.org/legal/src-headers.html#3party

**Comment by aditihilbert** [comment]
Neel, the conflicts got fixed. It took a while for asfgit to take it, that's all. 
Thanks!

**Comment by neelnatu** [comment]
Hi Justin,

On Thu, Mar 3, 2016 at 3:52 PM, Justin Mclean <notifications@github.com>
wrote:

> Hi,
>
> > The FreeBSD license is included in libs/os/include/os/os_time.h and
> > libs/util/src/datetime.c as required by that license. I also updated
> > LICENSES in the top level directory.
>
> Probably not quite correct as you have double headers on the files. While
> the software as a whole can be Apache licensed individual 3rd party files
> can be under other comparable licenses. But it can get a little tricky when
> your’ve taken a file and modified it - for Apache policy see [1].
>
> From [1] 1) do not remove license or copyright notices. 2) make sure the
> full text of the license in included somewhere 3) don’t add an Apache
> header unless major modifications have been made. We’re good with the first
> two points but the 3rd may need fixing.
>
> How much of those files are original?
>
>
Neither of the files were copied wholesale from FreeBSD (just the relevant
portions were cherry picked).

In terms of lines of code 'os_time.h' is 33% FreeBSD code and 'datetime.c'
is 37% FreeBSD code.

best
Neel

**Comment by justinmclean** [comment]
Hi,

> In terms of lines of code 'os_time.h' is 33% FreeBSD code and 'datetime.c'
> is 37% FreeBSD code.

Well then it's up the PMC what should be done, if they are unsure they can ask on legal discuss. IMO (INAL etc etc) having the double header is fine. You may have to add a small note before the BSD header saying “Some portions …” to make it clear the majority is Apache licensed and give a link to the original code. (Not legally require but just being nice.)

Thanks,
Justin

**Pull request closed without merging**
